Repository duozone-1-finalproject/Frontend, pull requests merged in 2025-09, with the labels that each got.

#42 data.data
  src/api/securitiesApi.ts
  src/service/securitiesDataService.ts
  src/types/securities.ts
Labels: enhancement

#44 Feat/#41 aitest
  src/components/dart-viewer/document-viewer.tsx
  src/hooks/dart-viewer/useSecuritiesGeneration.ts
Labels: bug

#48 사업보고서 2부 삽입기능 병합
  src/api/securitiesApi.ts
  src/hooks/dart-viewer/useSecuritiesGeneration.ts
  src/lib/dartViewerHelpers.ts
  src/service/dartViewerService.ts
  src/service/securitiesDataService.ts
  src/types/dartViewer.ts
  src/types/securities.ts
Labels: documentation

#52 axios 경로 변경
  src/App.tsx
  src/api/axios.ts
  src/api/dartViewerApi.ts
  src/components/main/Modal.tsx
  src/lib/dartViewerHelpers.ts
Labels: documentation

#60 프론트 용량 문제 해결
  src/api/dartViewerApi.ts
  src/service/dartViewerService.ts
  src/service/securitiesDataService.ts
  src/types/securities.ts
Labels: bug, enhancement
